### ISSUE TITLE
Use Timewarrior DOM for easier parsing

### ISSUE THREAD

**Issue by pbeckingham** [tassos/timewarrior-indicator#3]
I have a suggestion which would allow simpler parsing using the Timewarrior DOM to provide the information in machine-readable form.

To determine whether time tracking is currently active, use `dom.active`, which will yield a `0` or `1`:

    $ timew get dom.active
    1

If time tracking is active, use `dom.active.json` to provide all the details of the active interval, in JSON form:

    $ timew get dom.active.json
    {"start":"20170422T140233Z","tags":["Design command syntax","ti","ti.120"]}

**Comment by tassos** [comment]
That's a very good suggestion. I was not aware of the DOM of timewarrior, and the json format makes things much easier.

I will implement this in the next version! Thanks a lot!

**Comment by tassos** [comment]
I tried to implement your suggestion, but I am a bit stuck. The problem is with the datetime format that timew is returning. It seems really tricky to parse it with javascript using existing methods. Would you happen to have a suggestion on how could I parse it so that I compare it against the current datetime and print the duration of the activity?

Thanks for any ideas!

**Comment by pbeckingham** [comment]
The date format is one of the ISO-8601 standard formats, which is almost 30 years old.  It's a fixed-length, easy to parse format, so there should be no problem.  I see several StackOverflow questions/answers about this.

**Comment by tassos** [comment]
Well, I have found a lot of resources for the ISO-8601 extended format (2017-05-04T16:34:45Z), but not the basic one (20170504T163445Z), which is what timew gives as output.

But I will keep on looking...

**Comment by tassos** [comment]
Hi @pbeckingham , would you be able to share one of the resources you found on this issue? Cause I am totally blocked. Thanks!

**Comment by tassos** [comment]
In the end I realised there is no premade solution, and I wrote a function to parse the result, based on some help I got from stackoverflow. This was totally solved on f2b7ecf2.
