### ISSUE TITLE
broken with gnome 3.22

### ISSUE THREAD

**Issue by marcolaux** [tassos/timewarrior-indicator#4]
I'm not able to install or activate -from extensions.gnome.org- because of this error in gnome 3.22:

JS ERROR: Exception in callback for signal: extension-found: SyntaxError: missing : after property id @ /home/marcaux/.local/share/gnome-shell/extensions/timewarrior_indicator@natsakis.com/extension.js:88

`: function`
is missing

**Comment by tassos** [comment]
Hmmm... I originally developed the extensions for gnome 3.22, but eventually I upgraded it for 3.24. Probably something broke along the way...

I will have a look and come back to you in the following days, thank you for reporting this!

**Comment by marcolaux** [comment]
I guess they updated GJS for gnome 3.24. Perhaps it has to do with this.
The previous weeks I used gnome 3.24 and I confirm that it worked. Sadly I had to downgrade.

I fixed it myself in the meantime so I'm good for now :)

**Comment by tassos** [comment]
Okay, thanks for confirming that it works for 3.24. Indeed, I changed something to address the new GJS version of gnome 3.24, I was defining a variable twice or something.

Could you maybe post here how you solved the issue for you, in case someone else has the same issue? Thanks!

**Comment by marcolaux** [comment]
I'm kind of new to github - didn't do any pulls or something. I tried to make a new pull request and merge the changes there.
If that's confusing here is what i have changed:

Line 88:
`_zeroPad(num){`
should be:
`_zeroPad: function(num){`

I hope that helps :)

**Comment by tassos** [comment]
It's totally clear! Actually, the way _zeroPad function was defined, was a mistake from my side. I am quite surprised it worked with the new GJS. I merged the pull request, so your bug-fix will be included in the new version of the app.

Thanks a lot!
