### ISSUE TITLE
README wrong directory name

### ISSUE THREAD

**Issue by marcolaux** [tassos/timewarrior-indicator#6]
Hello again,

it's not really a bug but perhaps an issue. In the README it's written that a directory called "timewarrior-indicator@natsakis.com" (hyphen) should be created but in the metadate it's "timewarrior_indicator@natsakis.com" (underscore).

`JS ERROR: Could not load extension timewarrior-indicator@natsakis.com: Error: uuid "timewarrior_indicator@natsakis.com" from metadata.json does not match directory name "timewarrior-indicator@natsakis.com"`

I just wanted to reinstall from extensions.gnome.org but perhaps it's not the up to date one. Or it does not install because of this (gets deleted immediately when I try to enable it from there).

**Comment by tassos** [comment]
You are right! There is a mismatch between what is written in the README and what is in the metadata.json. Normally, the installation through extensions.gnome.org should work, but indeed, if you clone this repository, it makes the folder with an underscore.

I fixed that in 885307c and it will soon be updated at extensions.gnome.org
