### ISSUE TITLE
Doesnt work for 18.10

### ISSUE THREAD

**Issue by mathewjpotter** [tassos/timewarrior-indicator#7]
can't seem to get it working with ubuntu 18.10

**Comment by mathewjpotter** [comment]
I dug in into the code yesterday, clone the repo in the extension directly and tried to get it to boot this was the error I got

![Screenshot from 2019-03-20 08-20-50](https://user-images.githubusercontent.com/977008/54691642-38113d00-4ae9-11e9-941c-0faaaf87928b.png)

**Comment by mathewjpotter** [comment]
I tried updated files with the correct shell version of 3.30.1 as well

**Comment by lumbric** [comment]
I tried to make this extension working for GNOME Shell 42 in #9.
